cmake_minimum_required(VERSION 3.8)
project(spp_boundary_observer)
find_package(ament_cmake REQUIRED)
find_package(nav2_core REQUIRED)
find_package(nav2_msgs REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
add_library(spp_boundary_observer SHARED observer.cpp)
target_compile_features(spp_boundary_observer PUBLIC cxx_std_17)
ament_target_dependencies(spp_boundary_observer nav2_core nav2_msgs pluginlib rclcpp rclcpp_lifecycle)
pluginlib_export_plugin_description_file(nav2_core plugins.xml)
install(TARGETS spp_boundary_observer LIBRARY DESTINATION lib)
ament_package()
