"""Experimental SPP Conformance and Admission reference implementation."""

from .engine import (
    ReplayRegistry,
    admit,
    build_evidence,
    compute_requirement_delta,
    derive_plan,
    execute_plan,
    load_requirement_set,
    reset_replay_registry,
)

__all__ = [
    "EvidenceRecord",
    "Sufficiency",
    "assess_sufficiency",
    "derive_requalification_plan",
    "admit",
    "admit_evidence_backed",
    "admit_verified_evidence_backed",
    "admit_verified_policy_evidence_backed",
    "derive_verified_plan",
    "ReplayRegistry",
    "build_evidence",
    "compute_requirement_delta",
    "derive_plan",
    "execute_plan",
    "load_requirement_set",
    "reset_replay_registry",
    "ConformanceProvider",
    "MappingSelection",
    "RequirementMappingRegistry",
    "DEFAULT_REQUIREMENT_MAPPING_REGISTRY",
    "EVIDENCE_BUNDLE_TYPE",
    "PLACE_REQUIREMENTS_TYPE",
    "SignedEvidence",
    "SignedPlaceRequirements",
    "SignedEvidenceRecord",
    "SignatureVerification",
    "PolicySignatureVerification",
    "TrustedIssuer",
    "TrustedIssuerRegistry",
    "TrustedPolicyAuthority",
    "TrustedPolicyAuthorityRegistry",
    "evidence_scope",
    "policy_scope",
    "sign_evidence",
    "sign_place_requirements",
    "verify_signed_evidence",
    "verify_signed_place_requirements",
    "ProfileLifecycleAssessment",
    "ProfileRevocationRegistry",
    "assess_profile_lifecycle",
    "profile_identifier",
    "PLACE_PACKAGE_VERSION",
    "PlacePackageVerification",
    "create_place_package",
    "serialize_place_package",
    "load_place_package",
    "verify_place_package",
    "ASSURANCE_LEVELS",
    "ConformanceProviderDescriptor",
    "ConformanceProviderResult",
    "ExternalConformanceProvider",
    "ProviderSelection",
    "ConformanceProviderRegistry",
    "RequirementDefinition",
    "RequirementResolution",
    "RequirementVocabularyRegistry",
    "DEFAULT_REQUIREMENT_VOCABULARY",
    "BUILTIN_REQUIREMENTS",
    "requirements_compatible",
    "FacilityAccessDecision",
    "ReferenceDoorController",
    "map_profile_to_access",
]

from .sufficiency import EvidenceRecord, Sufficiency, assess_sufficiency, derive_requalification_plan
from .boundary import admit_evidence_backed, admit_verified_evidence_backed, admit_verified_policy_evidence_backed, derive_verified_plan
from .trust import (
    EVIDENCE_BUNDLE_TYPE,
    PLACE_REQUIREMENTS_TYPE,
    PolicySignatureVerification,
    SignedEvidence,
    SignedPlaceRequirements,
    SignedEvidenceRecord,
    SignatureVerification,
    TrustedIssuer,
    TrustedIssuerRegistry,
    TrustedPolicyAuthority,
    TrustedPolicyAuthorityRegistry,
    evidence_scope,
    policy_scope,
    sign_evidence,
    sign_place_requirements,
    verify_signed_evidence,
    verify_signed_place_requirements,
)
from .mapping import (
    ConformanceProvider,
    DEFAULT_REQUIREMENT_MAPPING_REGISTRY,
    MappingSelection,
    RequirementMappingRegistry,
)
from .lifecycle import (
    ProfileLifecycleAssessment,
    ProfileRevocationRegistry,
    assess_profile_lifecycle,
    profile_identifier,
)
from .place_package import (
    PLACE_PACKAGE_VERSION,
    PlacePackageVerification,
    create_place_package,
    serialize_place_package,
    load_place_package,
    verify_place_package,
)
from .providers import (
    ASSURANCE_LEVELS,
    ConformanceProviderDescriptor,
    ConformanceProviderResult,
    ExternalConformanceProvider,
    ProviderSelection,
    ConformanceProviderRegistry,
)
from .vocabulary import (
    BUILTIN_REQUIREMENTS,
    DEFAULT_REQUIREMENT_VOCABULARY,
    RequirementDefinition,
    RequirementResolution,
    RequirementVocabularyRegistry,
    requirements_compatible,
)
from .facility_access import FacilityAccessDecision, ReferenceDoorController, map_profile_to_access
